steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --no-cache \
          --build-arg NEXT_PUBLIC_GOOGLE_PLACES_API_KEY=$$NEXT_PUBLIC_GOOGLE_PLACES_API_KEY \
          --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=$$NEXT_PUBLIC_FIREBASE_API_KEY \
          --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
          --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$NEXT_PUBLIC_FIREBASE_PROJECT_ID \
          --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \
          --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \
          --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=$$NEXT_PUBLIC_FIREBASE_APP_ID \
          -t $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA \
          . -f Dockerfile
    id: Build
    entrypoint: bash
    secretEnv:
      - NEXT_PUBLIC_GOOGLE_PLACES_API_KEY
      - NEXT_PUBLIC_FIREBASE_API_KEY
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      - NEXT_PUBLIC_FIREBASE_APP_ID

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--set-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest'
      - '--set-secrets'
      - 'GOOGLE_PLACES_API_KEY=GOOGLE_PLACES_API_KEY:latest'
      - '--set-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest'
      - '--set-secrets'
      - 'FIREBASE_ADMIN_PROJECT_ID=FIREBASE_ADMIN_PROJECT_ID:latest'
      - '--set-secrets'
      - 'FIREBASE_ADMIN_PRIVATE_KEY=FIREBASE_ADMIN_PRIVATE_KEY:latest'
      - '--set-secrets'
      - 'FIREBASE_ADMIN_CLIENT_EMAIL=FIREBASE_ADMIN_CLIENT_EMAIL:latest'
    id: Deploy
    secretEnv:
      - OPENAI_API_KEY
      - GOOGLE_PLACES_API_KEY
      - GEMINI_API_KEY
      - FIREBASE_ADMIN_PROJECT_ID
      - FIREBASE_ADMIN_PRIVATE_KEY
      - FIREBASE_ADMIN_CLIENT_EMAIL

images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_GOOGLE_PLACES_API_KEY/versions/latest
      env: NEXT_PUBLIC_GOOGLE_PLACES_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
      env: OPENAI_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_PLACES_API_KEY/versions/latest
      env: GOOGLE_PLACES_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
      env: GEMINI_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      env: NEXT_PUBLIC_FIREBASE_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      env: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      env: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      env: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      env: NEXT_PUBLIC_FIREBASE_APP_ID
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_ADMIN_PROJECT_ID/versions/latest
      env: FIREBASE_ADMIN_PROJECT_ID
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_ADMIN_PRIVATE_KEY/versions/latest
      env: FIREBASE_ADMIN_PRIVATE_KEY
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_ADMIN_CLIENT_EMAIL/versions/latest
      env: FIREBASE_ADMIN_CLIENT_EMAIL

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: plan-my-trip
  REPO_NAME: plan-my-trip
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _PLATFORM: managed
  _TRIGGER_ID: 586b1c24-d7d4-41ce-a4ac-57c5f6fcaa11

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - plan-my-trip
